### PR TITLE
Ran generator.dart file to update the fonts for the flutter package

### PR DESCRIPTION
**Pull request by wildaces215**
@clocksmith @johnsonmh Please review the git commit if there is anything else that is needed please let me know!

### CODE REVIEW

**Comment by wildaces215** [comment]
@googlebot I signed it!

**Comment by mzdm** [comment]
No fonts were added in this generation tho?

**Comment by wildaces215** [comment]
I believe it did as I ran the genrator.dart file

**Comment by clocksmith** [comment]
If this did add new fonts, `lib/google_fonts.dart` should have changes.

**Comment by wildaces215** [comment]
Then I'll close it and resubmit the pull request with my font family that I have put in the issues then!Thank you!

**Pull request closed without merging**
