### PR TITLE
Fix path_provider usage for web

### PR DESCRIPTION
**Pull request by jld3103**
Fix app on web getting stuck for a few seconds on trying to get the application support directory.

### CODE REVIEW

**Comment by jld3103** [comment]
Ah great. Then it should be very easy

**Comment by jld3103** [comment]
@clocksmith How do I create a test with `kIsWeb` set?

**Comment by clocksmith** [comment]
@jld3103 good question. I think we may need to create an abstract class / interface, let's call it `WebChecker` that has a method `bool isWeb()`. Then create an impl of this interface that is `isWeb() => kIsWeb;` and use it to replace all kIsWeb references in the src. Then, a mock can be made in the test that is forced to return true for isWeb().

See 
* https://github.com/material-foundation/google-fonts-flutter/blob/master/lib/src/google_fonts_base.dart#L25
* https://github.com/material-foundation/google-fonts-flutter/blob/master/test/load_font_if_necessary_test.dart#L40

**Comment by clocksmith** [comment]
Updated my last comment with a simpler solution

**Comment by jld3103** [comment]
@clocksmith added tests and resolved conflicts

**Comment by johnsonmh** [comment]
Version [0.3.9](https://pub.dev/packages/google_fonts/versions/0.3.9) is live, thank you again for the contribution!

**Pull request merged**
