### PR TITLE
Prepare for null-safe v2.0.0

### PR DESCRIPTION
**Pull request by kevmoo**
Remove changelog bits that don't affect end-users
Updates for latest changes in path_provider

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @clocksmith

**Comment by gaetschwartz** [comment]
@kevmoo Would be great to also fix https://github.com/material-foundation/google-fonts-flutter/issues/146 as it is prevents `google_fonts` from working and has a simple fix. Can make a PR if needed.

**Comment by kevmoo** [comment]
Seems like a good idea to tackle #146 first.

@clocksmith ? @pennzht ?

**Comment by gaetschwartz** [comment]
Made a PR here https://github.com/material-foundation/google-fonts-flutter/pull/149 :)

**Review by clocksmith — APPROVED** [review]

**Pull request merged**
